### ISSUE TITLE
add server port to spring configuration

### ISSUE THREAD

**Issue by albertoSoto** [ivangfr/springboot-react-keycloak#18]
First of all, thanks, super nice approach.

I realized you are missing the following for the local dev environment, so it does not collide spring boot port with kc

Under application.yml for spring services you could add the following, to launch the react dashboard directly

`server:
  port: 9080`

**Comment by ivangfr** [comment]
Hi @albertoSoto thanks for the message.

In fact, I am setting the port at runtime as described in the [README](https://github.com/ivangfr/springboot-react-keycloak#running-movies-app-using-maven--npm) by starting the app using Maven with the following command, where I inform the port:
```
./mvnw clean spring-boot:run -Dspring-boot.run.jvmArguments="-Dserver.port=9080"
```

Best regards,
