### ISSUE TITLE
Upgrading to Keycloak 17 results in 401 Auth issue when listing Realms

### ISSUE THREAD

**Issue by jeffreyporter** [ivangfr/springboot-react-keycloak#8]
Upgrading to Keycloak 17 results in 401 Auth issue when listing Realms.

I know this is more of a wish then a defect, but I've been using this project a test and would like to upgrade to Keycloak 17 and have issues.

When I find out why I get the Auth issue with 17 I will feed it back here, and hope to create a PR to update this project.

**Comment by ivangfr** [comment]
Hi @jeffreyporter 

I didn't know about `Keycloak` version `17`. I've just updated the project to use this new version.

Thanks!
