### ISSUE TITLE
Deprecation of Keycloak adapters

### ISSUE THREAD

**Issue by ccaspanello** [ivangfr/springboot-react-keycloak#9]
With the deprecation of the keycloak adapters I was wondering if you would be able to provide an update or a seperate example of how to handle this without the keycloak adapater.
https://www.keycloak.org/2022/02/adapter-deprecation.html

**Comment by ivangfr** [comment]
Hi @ccaspanello Thanks for sharing it. I will have a look when I have some free time.

**Comment by ccaspanello** [comment]
Awesome. Thank you very much h @ivangfr  !

**Comment by ivangfr** [comment]
Hi @ccaspanello I've replaced the **Keycloak Adapter** in the backend application, `movies-api`, by Oauth2 Resource Server. I will keep for now the Keycloak npm packages used in the frontend application, `movies-ui`.

**Comment by ccaspanello** [comment]
Woah, that was quick.  You rock!  The frontend package isn't deprecated so that sounds fine.  I like the way you did it.  Nice and clean.
